esphome:
  name: "smart-touch-1"
  friendly_name: Smart Touch Lamp 1
  compile_process_limit: 1

esp32:
  board: esp32doit-devkit-v1
  # minimum_chip_revision: "3.1"
  # board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:
  level: info
#  level: debug

# Enable Home Assistant API
api:
  # encryption:
  #   key: !secret api_key

ota:
  - platform: esphome
    # password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # manual_ip:
  #   static_ip: 192.168.2.57
  #   gateway: 192.168.2.1
  #   subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "FR-Lamp-Touch"
    password: !secret wifi_password

# Enable Web server.
web_server:
  port: 80
  
captive_portal:


esp32_touch:
  setup_mode: false
  # measurement_duration: 0.25ms
  
binary_sensor:
  - platform: esp32_touch
    name: "Touch Pad Pin 13"
    pin: GPIO13
    threshold: 700
    # filters:
    #   # Small filter, to debounce the spurious events.
    #   - delayed_on: 10ms
    #   - delayed_off: 10ms
    #on_press:
    on_click:
    - min_length: 10ms
      max_length: 500ms
      # Short touch to cycle through brightnesses
      then:
        - number.increment:
            id: dimmer_control
            cycle: true
number:     
  - platform: template
    name: Dimmer Control
    id: dimmer_control
    min_value: 0
    max_value: 100
    step: 25
    optimistic: true
    set_action:
      then:
        - light.turn_on:
            id: dimmer
            brightness: !lambda 'return x / 100.0;'

# restart-button
button:
  - platform: restart
    name: "restart-esp32-dim-touch"

# AC Dimmer Configuration
light:
  - platform: monochromatic
    id: dimmer
    name: "Smart Lamp"
    output: ac_dimmer_output
    # restore_mode: ALWAYS_ON
    #on_turn_on:  IS THIS NEEDED??
    #  - light.turn_on:
    #      id: dimmer
    #      brightness: 1.0  # Set initial brightness to 100% on power up

output:
  - platform: ac_dimmer
    id: ac_dimmer_output
    gate_pin: GPIO25  # Gate pin for controlling the dimmer (GPIO12)
    zero_cross_pin:
      number: GPIO18  # Zero-cross pin for synchronization (GPIO5)
      mode:
        input: True
        pullup: True
      inverted: yes
